# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3

# Fabric API
fabric_version=0.153.0+26.2

# Mod Properties
mod_version=2.1.0
maven_group=xyz.imcodist.quickmenu
archives_base_name=quick-menu

# YACL
yacl_version=3.9.5+26.2-fabric

# Mod Menu
mod_menu_version=20.0.0-beta.3

# Kotlin
kotlin_version=2.4.0
fabric_language_kotlin_version=1.13.12+kotlin.2.4.0
